# SEO Settings
title: InvestSmart - Educação Financeira e Investimentos
description: Plataforma de educação financeira e investimentos para ajudar você a tomar decisões financeiras inteligentes e construir um futuro próspero.
url: https://lcodebase.github.io/InvestSmart/
author: InvestSmart
logo: /images/Camada 1.png

# Social Media
social:
  twitter: investsmart
  facebook: investsmart
  instagram: investsmart
  linkedin: investsmart

# SEO Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
