# Site settings
title: InvestSmart
description: "Plataforma completa para gestão financeira pessoal que combina organização prática com insights inteligentes para otimizar suas finanças."
baseurl: "/InvestSmart"
url: "https://lcodebase.github.io"

# SEO settings
lang: pt-BR
author: LCodeBase
twitter:
  username: your-twitter-handle
  card: summary_large_image
social:
  name: InvestSmart
  links:
    - https://github.com/LcodeBase/InvestSmart

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title.html

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "noticia"
      image: /images/default-post-image.png

# Adicione estas configurações ao seu _config.yml existente
paginate: 9
paginate_path: "/noticias/pagina/:num/"

# Plugins necessários
plugins:
  - jekyll-paginate
