# Configurações do Site
title: InvestSmart - Gestão Financeira Inteligente
description: Plataforma completa de educação financeira e investimentos com ferramentas de gestão financeira, recomendações personalizadas e conteúdo educacional atualizado.
## Step 4: Update all other pages

You'll need to update all other HTML files in your project that link to blogs-main.html. Make sure to use the absolute path with your repository name: `/InvestSmart/noticias.html` instead of the relative path `blogs-main.html`.

## Step 5: Check your _config.yml file

Make sure your _config.yml has the correct baseurl setting:
```yaml
# Add or update this line in your _config.yml
baseurl: "/InvestSmart"
```
url: "https://lcodebase.github.io"
lang: pt-BR

# Configurações de SEO
author: InvestSmart
logo: /images/Camada 1.png
social:
  name: InvestSmart
  links:
    - https://facebook.com/investsmart
    - https://instagram.com/investsmart
    - https://youtube.com/investsmart

# Configurações de Permalink
permalink: /:categories/:year/:month/:day/:title/

# Configurações de Coleções
collections:
  posts:
    output: true

# Configurações de Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Configurações de Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "noticia"
      author: "InvestSmart"
      
# Configurações de Paginação
paginate: 9
paginate_path: "/blog/page:num/"
